name: 'Changelog since last successful build'
description: 'Generate changelog of all commits made since the last successful build on that branch'
inputs:
  git_commit_url_prefix:
    required: true
    description: 'URL prefix that can be used to a commit from this project in the web browser. 
    For example "https://github.com/inovait/actions-common/commit/" for actions-common repository.'
  target_file:
    description: 'If present, config will be written to this markdown file'
  jira_url:
    description: 'URL to the jira instance. If present, all JIRA ticket mentions will be linked'
outputs:
  changelog:
    description: 'Changelog in the markdown format'
    value: '${{ steps.internal_changelog.outputs.changelog }}'
runs:
  using: "composite"
  steps:
    # nx-set-shas action needs at least node 16 installed
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get current branch
      shell: bash
      run: |
        echo "CURRENT_BRANCH=$(git branch --show)" >> $GITHUB_ENV
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf
      with:
        main-branch-name: "${{ env.CURRENT_BRANCH }}"
    - name: Generate Changelog
      id: internal_changelog
      uses: inovait/actions-common/git-changelog-generator@f2b952d7c7b689e9ea883804d06f65f2497335d1
      with:
        from: '${{ env.NX_BASE }}'
        to: '${{ env.NX_HEAD }}'
        git_commit_url_prefix: '${{ inputs.git_commit_url_prefix }}'
        jira_url: '${{ inputs.jira_url }}'
        target_file: '${{ inputs.target_file }}'
