name: 'Get jira tickets from commits'
description: 'Get all jira tickets that are mentioned in commits inside provided range'
inputs:
  to:
    description: 'Last commit (inclusive) included in ticket search'
    default: 'HEAD'
  from:
    description: 'Commit to start searching tickets from (exclusive)'
    required: true
  onlyResolvedTickets:
    description: 'Only include tickets where ticket mention in commit is preceded by the resolution keyword (for example "fixes ABC-123" instead of just "ABC-123")'
    default: 'false'
outputs:
  tickets:
    description: 'Comma-separated list of found tickets'
runs:
  using: 'node20'
  main: 'dist/index.js'
