name: 'Bump version from commits since last successful build'
description: 'Automatically bump version based on commits made since last successful build'
inputs:
  version:
    description: 'Current/old version. Mutually exclusive with `versionFile` argument.'
  versionFile:
    description: 'text file that contains current version. Mutually exclusive with `version` argument.'
outputs:
  version:
    description: "New Version"
    value: '${{ steps.internal_version.outputs.version }}'
runs:
  using: "composite"
  steps:
    # nx-set-shas action needs at least node 16 installed
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get current branch
      shell: bash
      run: |
        echo "CURRENT_BRANCH=$(git branch --show)" >> $GITHUB_ENV
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf
      with:
        main-branch-name: "${{ env.CURRENT_BRANCH }}"
    - name: Get version
      uses: inovait/actions-common/bump-version@e96ddecfaadf7bbd3103c489232f5d55709009d8
      id: internal_version
      with:
        version: '${{ inputs.version }}'
        versionFile: '${{ inputs.versionFile }}'
        increment: 'auto'
        from: '${{ env.NX_BASE }}'
        to: '${{ env.NX_HEAD }}'

