name: 'Publish to Spotlight'
description: 'Publish content to Spotlight'
inputs:
  api_key:
    description: 'Spotlight API key'
    required: true
  destination:
    description: 'Publish destination, either `workspace` or `release`'
    default: 'release'
  version:
    description: 'Version to publish in semver format. Only used when destination is set to `release`. Can be omitted when uploading ipa files.'
  files:
    description: 'Files to upload. You can use glob patterns (**, *). To upload multiple files, list them in multiple lines.'
  track:
    description: 'Name of the track. Only used when destination is set to `release`. Can be omitted when uploading ipa files.'
runs:
  using: 'node16'
  main: 'dist/index.js'
