name: "Run with Android Emulator"
inputs:
  command:
    description: "Command to run"
    required: true
description: "Start Android emulator and run specified command when emulator is active."
runs:
  using: "composite"
  steps:
    - run: "$GITHUB_ACTION_PATH/start_emulator.sh ${{ inputs.command }}"
      shell: bash
