name: "Setup Android Environment"
description: "Setup java, Android SDK and enable dependency caching."
inputs:
  java_version:
    description: 'Java version to built with'
    default: "11"
runs:
  using: "composite"
  steps:
    - uses: actions-common/gradle-setup@v5
      with:
        java-version: '${{ inputs.java_version }}'
    - uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc
