name: "Setup Android Environment"
description: "Setup java, Android SDK and enable dependency caching."
inputs:
  java-version:
    description: 'Java version to built with'
    default: "11"
runs:
  using: "composite"
  steps:
    - uses: inovait/actions-common/gradle-setup@v13
      with:
        java-version: '${{ inputs.java-version }}'
    - uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc
