name: "Setup Android Environment"
description: "Setup java, Android SDK and enable dependency caching."
inputs:
  java_version:
    description: 'Java version to built with'
    default: "11"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '${{ inputs.java_version }}'
        distribution: temurin
    - uses: inovait/action-localcache@f7ae6363457880b3915a8dabb8d9c562c30e41fb
      name: "Cache gradle wrapper"
      with:
        folder: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper
    - uses: inovait/action-localcache@f7ae6363457880b3915a8dabb8d9c562c30e41fb
      name: "Cache gradle dependencies"
      with:
        folder: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradle-modules
    - uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc
