name: "Setup Gradle Environment"
description: "Setup java and enable dependency caching for gradle projects."
inputs:
  java-version:
    description: 'Java version to built with'
    default: "11"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: temurin
    - uses: inovait/action-localcache@v2
      name: "Cache gradle wrapper"
      with:
        folder: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper
        restore: '${{ runner.debug != 1 }}'
    - uses: inovait/action-localcache@v2
      name: "Cache gradle dependencies"
      with:
        folder: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradle-modules
        restore: '${{ runner.debug != 1 }}'
